patterns = {
    '@Bearlish and Bullish':'@Bearlish and Bullish',
    'CDLABANDONEDBABY':'Abandoned Baby',
    'CDLBELTHOLD':'Belt-hold',
    'CDLBREAKAWAY':'Breakaway',
    'CDLCLOSINGMARUBOZU':'Closing Marubozu',
    'CDLDOJI':'Doji',
    'CDLENGULFING':'Engulfing Pattern',
    'CDLHARAMI':'Harami Pattern',
    'CDLHARAMICROSS':'Harami Cross Pattern',
    'CDLKICKING':'Kicking',
    'CDLKICKINGBYLENGTH':'Kicking - bull/bear determined by the longer marubozu',
    'CDLLONGLEGGEDDOJI':'Long Legged Doji',
    'CDLMARUBOZU':'Marubozu',
    'CDLSEPARATINGLINES':'Separating Lines',
    'CDL3LINESTRIKE':'Three-Line Strike',
    'CDLTRISTAR':'Tristar Pattern',    
    '@Bearlish Only':'Bearlish Only',
    'CDLADVANCEBLOCK':'Advance Block', 
    'CDLDARKCLOUDCOVER':'Dark Cloud Cover',           
    'CDLGAPSIDESIDEWHITE':'Up/Down-gap side-by-side white lines',
    'CDLEVENINGDOJISTAR':'Evening Doji Star',
    'CDLEVENINGSTAR':'Evening Star',    
    'CDLHANGINGMAN':'Hanging Man',        
    'CDLIDENTICAL3CROWS':'Identical Three Crows',
    'CDLINNECK':'In-Neck Pattern',
    'CDLONNECK':'On-Neck Pattern',
    'CDLSHOOTINGSTAR':'Shooting Star',
    'CDL3BLACKCROWS':'Three Black Crows',    
    'CDL3OUTSIDE':'Three Outside Up/Down',        
    'CDLTHRUSTING':'Thrusting Pattern',        
    'CDL2CROWS':'Two Crows',
    'CDLUPSIDEGAP2CROWS':'Upside Gap Two Crows',
    '@Bullish Only':'@Bullish Only',
    'CDLCONCEALBABYSWALL':'Concealing Baby Swallow',
    'CDLHAMMER':'Hammer',
    'CDLHOMINGPIGEON':'Homing Pigeon',
    'CDLINVERTEDHAMMER':'Inverted Hammer',
    'CDLMATCHINGLOW':'Matching Low', 
    'CDLMATHOLD':'Mat Hold',
    'CDLMORNINGDOJISTAR':'Morning Doji Star',
    'CDLMORNINGSTAR':'Morning Star',    
    'CDLPIERCING':'Piercing Pattern',
    'CDLRISEFALL3METHODS':'Rising/Falling Three Methods',        
    'CDLSTICKSANDWICH':'Stick Sandwich',
    'CDL3INSIDE':'Three Inside Up/Down',
    'CDL3STARSINSOUTH':'Three Stars In The South',  
    'CDL3WHITESOLDIERS':'Three Advancing White Soldiers',        
    'CDLUNIQUE3RIVER':'Unique 3 River', 
    'CDLXSIDEGAP3METHODS':'Upside/Downside Gap Three Methods',   
    'CDLTASUKIGAP':'Tasuki Gap',
    '@Etc.':'@Etc.',
    'CDLCOUNTERATTACK':'Counterattack',    
    'CDLDOJISTAR':'Doji Star',
    'CDLDRAGONFLYDOJI':'Dragonfly Doji',            
    'CDLGRAVESTONEDOJI':'Gravestone Doji',    
    'CDLHIGHWAVE':'High-Wave Candle',
    'CDLHIKKAKE':'Hikkake Pattern',
    'CDLHIKKAKEMOD':'Modified Hikkake Pattern',        
    'CDLLADDERBOTTOM':'Ladder Bottom',    
    'CDLLONGLINE':'Long Line Candle',    
    'CDLRICKSHAWMAN':'Rickshaw Man',    
    'CDLSHORTLINE':'Short Line Candle',
    'CDLSPINNINGTOP':'Spinning Top',
    'CDLSTALLEDPATTERN':'Stalled Pattern',    
    'CDLTAKURI':'Takuri (Dragonfly Doji with very long lower shadow)',                
}